### ISSUE TITLE
failure on other code with : inside

### ISSUE THREAD

**Issue by pseudozach** [LCozzoli/SMS-Activate.org#1]
can you handle this response from API:

`STATUS_OK:Dein OpenAI API Sicherheitscode lautet: 194130`

in this case, it returns `Dein OpenAI API Sicherheitscode lautet` where it should return `Dein OpenAI API Sicherheitscode lautet: 194130`

**Comment by LCozzoli** [comment]
Hello, what API method is triggering this please?

**Comment by pseudozach** [comment]
getStatus, it's here, only happens if the response has two ":" instead of just one.
https://github.com/LCozzoli/SMS-Activate.org/blob/main/src/lib/parts/activations/routes/getStatus.ts#L24

**Comment by LCozzoli** [comment]
I just pushed the update. Thanks!
