### ISSUE TITLE
Can't get code

### ISSUE THREAD

**Issue by keadeish** [LCozzoli/SMS-Activate.org#3]
Hi,

`const code = await number.getCode();` does not work for me. the code just stops even though i can see the code on the SMS website.

**Comment by LCozzoli** [comment]
Hello, have you tried to increase the wait time ? number.getCode(300); for example ?
Edit: I will add this tomorrow it’s not implemented in the class yet

**Comment by keadeish** [comment]
thanks, i will let you know if it works when you update it!

**Comment by LCozzoli** [comment]
I pushed the little time setting

**Comment by LCozzoli** [comment]
Can you try to catch the error please ? do await number.getCode(300).catch(console.error)

**Comment by keadeish** [comment]
Hey,

I just tried it. Here is the code & issue:

***@***.***
***@***.***

**Comment by LCozzoli** [comment]
I think that you failed to post the reply on GitHub ahah

**Comment by keadeish** [comment]
aha sure. sorry.

```
try {
            /** Waiting a maximum of 180s for the code to arrive **/
            const code = await number.getCode(300).catch(console.error);
            console.log(`the code is: ${code}`)
            /** Setting code status to Success if everything worked as expected **/
            await number.success();
            await page.type('.ccl-3f330ce063d1da79', `${code}`)
            await page.click('.ccl-388f3fb1d79d6a36.ccl-6d2d597727bd7bab.ccl-59eced23a4d9e077.ccl-7be8185d0a980278')

        } catch (err) {
            console.error(err);

            /** Setting code status to Failed if the code was used **/
            await number.failed();
        }

    }).catch(console.error);
```
that's the code that i'm using & nothing gets executed past `const code`

**Comment by keadeish** [comment]
would you mind updating the Usage/Examples in the README file please?

copying the sample code into a ts file renders a lot of type errors,

**Comment by keadeish** [comment]
hey @LCozzoli any update? 
thanks :)

**Comment by nishuzumi** [comment]
Same issue

**Comment by nishuzumi** [comment]
@keadeish It looks like he has abandoned the project and I fixed the problem and uploaded it to a new repository. https://github.com/nishuzumi/sms-activate-sdk

**Comment by keadeish** [comment]
wow @nishuzumi thanks a lot ❤️ Do you have discord by any chance? I’m curious as to how you fixed it so soon.

**Comment by nishuzumi** [comment]
> wow @nishuzumi thanks a lot ❤️ Do you have discord by any chance? I’m curious as to how you fixed it so soon.

My discord is Box#3338. No tricks, just one debug after another

**Comment by LCozzoli** [comment]
Oops sorry guys I’m quite busy with private work, glad that you fixed it @nishuzumi 👍

**Comment by LCozzoli** [comment]
Not very nice to add your referral code in the code but well ahaha, I’ll patch my project, you can pull request without the referral code if you desire
