### ISSUE TITLE
code cut off at https:

### ISSUE THREAD

**Issue by pseudozach** [LCozzoli/SMS-Activate.org#4]
issue with parsing response,
this is the response from api:
>Spark Wallet Verification :. Please click the link to verify your mobile phone number. https://link.sparkwallet.io/somesecretcode

but what arrives: 
>Spark Wallet Verification :. Please click the link to verify your mobile phone number. https:

again because of the way this library checks for `:` and splits them. I think it should just send everything after the response is parsed.

**Comment by LCozzoli** [comment]
It splits after the STATUS_OK:
Based on their api doc, `STATUS_OK: 'activation code' - code received`
https://sms-activate.org/api2#getStatus
I'll check to see what they send, strange

**Comment by LCozzoli** [comment]
I'm sorry but I don't seems to find "sparkwallet" in their service list, I wanted to try by myself but I can't. I pushed an update that might fix your issue. You can enable SMS_ACTIVATE_DEBUG=true in a .env file to look for debugs if you desire.

**Comment by pseudozach** [comment]
in this case, it's a message coming from "any other" which means it can be any free form text including URLs.
thanks I'll update and test again.
