### ISSUE TITLE
ACCESS_NUMBER in getnumber response

### ISSUE THREAD

**Issue by pseudozach** [LCozzoli/SMS-Activate.org#6]
sorry to bug you again but I just noticed they started returning ACCESS_NUMBER in getNumber endpoint and this library is returning SERVER_ERROR...

running this command:
axios.get(`https://sms-activate.ru/stubs/handler_api.php?api_key=${SMSActivateAPIKEY}&action=getNumber&service=${service}&country=${country}`)
returns this response:
ACCESS_NUMBER:122xxx:62895xxxx

so when this is called:
`smsActivateOrgApi.getNumber({country, service})` it returns `SERVER_ERROR`

because I think it doesn't find all the other things in the response string.

**Comment by LCozzoli** [comment]
Hm it uses `getNumberV2` 
https://github.com/LCozzoli/SMS-Activate.org/blob/main/src/lib/parts/activations/routes/getNumberV2.ts
Can you add `SMS_ACTIVATE_DEBUG=true` in your .env please? and check what you receive from the API exactly

**Comment by pseudozach** [comment]
hm I missed it. it's returning regular response now. will report if it happens again or we can close it.

**Comment by LCozzoli** [comment]
I think it was a server issue from the website yeap
